Add admin dashboard frame and fix whitespace

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -15,79 +15,79 @@ SSH_NOT_REACHABLE_MESSAGE="SSH server not reachable"
 REMOTE=$1
 
 Cleanup () {
-    rm -f $TMP_FILE
-    rm -f $TMP_ARCHIVE
+        rm -f $TMP_FILE
+        rm -f $TMP_ARCHIVE
 }
 
 Cleanup
 
 Verify () {
-    echo "Verifying system programs"
+        echo "Verifying system programs"
 
-    # Verify ping exists
-    if ! type "ping" > /dev/null 2> /dev/null; then
-        echo "ERROR: ping can't be called" 1>&2
-        Cleanup
-       exit 1
-    fi
+        # Verify ping exists
+        if ! type "ping" > /dev/null 2> /dev/null; then
+                echo "ERROR: ping can't be called" 1>&2
+                Cleanup
+           exit 1
+        fi
 
-    # Verify Server is Online
-    echo "Testing server ping"
-    ping -q -c 1 $REMOTE > /dev/null
-    if [ $? -ne 0 ]; then
-        echo $NOT_REACHABLE_MESSAGE
-        Cleanup
-        exit 1
-    fi
+        # Verify Server is Online
+        echo "Testing server ping"
+        ping -q -c 1 $REMOTE > /dev/null
+        if [ $? -ne 0 ]; then
+                echo $NOT_REACHABLE_MESSAGE
+                Cleanup
+                exit 1
+        fi
 
-    # Verify ssh exists
-    if ! type "ssh" > /dev/null 2> /dev/null; then
-        echo "ERROR: ssh can't be called" 1>&2
-        Cleanup
-        exit 1
-    fi
+        # Verify ssh exists
+        if ! type "ssh" > /dev/null 2> /dev/null; then
+                echo "ERROR: ssh can't be called" 1>&2
+                Cleanup
+                exit 1
+        fi
 
-    # Verify scp exists
-    if ! type "scp" > /dev/null 2> /dev/null; then
-        echo "ERROR: scp can't be called" 1>&2
-        Cleanup
-        exit 1
-    fi
+        # Verify scp exists
+        if ! type "scp" > /dev/null 2> /dev/null; then
+                echo "ERROR: scp can't be called" 1>&2
+                Cleanup
+                exit 1
+        fi
 
-    # Verify remote has ssh server
-    echo "Tesing remote SSH server"
-    ssh -q $REMOTE "exit"
-    if [ $? -ne 0 ]; then
-        echo $SSH_NOT_REACHABLE_MESSAGE
-        Cleanup
-        exit 1
-    fi
+        # Verify remote has ssh server
+        echo "Tesing remote SSH server"
+        ssh -q $REMOTE "exit"
+        if [ $? -ne 0 ]; then
+                echo $SSH_NOT_REACHABLE_MESSAGE
+                Cleanup
+                exit 1
+        fi
 
-    # Verify find exists
-    if ! type "find" > /dev/null 2> /dev/null; then
-        echo "ERROR: find can't be called" 1>&2
-        Cleanup
-        exit 1
-    fi
+        # Verify find exists
+        if ! type "find" > /dev/null 2> /dev/null; then
+                echo "ERROR: find can't be called" 1>&2
+                Cleanup
+                exit 1
+        fi
 
-    # Verify tar exists
-    if ! type "tar" > /dev/null 2> /dev/null; then
-        echo "ERROR: tar can't be called" 1>&2
-        Cleanup
-        exit 1
-    fi
+        # Verify tar exists
+        if ! type "tar" > /dev/null 2> /dev/null; then
+                echo "ERROR: tar can't be called" 1>&2
+                Cleanup
+                exit 1
+        fi
 
-    # Verify xargs exists
-    if ! type "xargs" > /dev/null 2> /dev/null; then
-        echo "ERROR: xargs can't be called" 1>&2
-        Cleanup
-        exit 1
-    fi
+        # Verify xargs exists
+        if ! type "xargs" > /dev/null 2> /dev/null; then
+                echo "ERROR: xargs can't be called" 1>&2
+                Cleanup
+                exit 1
+        fi
 }
 
 Remote_Clean () {
-    echo "Cleaning remote"
-    ssh $REMOTE "rm -rf $REMOTE_WWW/*"
+        echo "Cleaning remote"
+        ssh $REMOTE "rm -rf $REMOTE_WWW/*"
 }
 
 ##########################
@@ -96,22 +96,22 @@ Remote_Clean () {
 
 # Verify Arguments
 if [ $# -ne 1 ]; then
-    # Check if valid extra args
-    if [ $# -ne 2 ]; then
-        echo "Invalid number of arguments"
-        echo $USAGE
-        Cleanup
-        exit 1
-    else
-        # Check if clean operation
-        if [ $2 == $CLEAN_TAG ]; then
-            # Clean tag added
-            Verify
-            Remote_Clean
-            Cleanup
-            exit 0
+        # Check if valid extra args
+        if [ $# -ne 2 ]; then
+                echo "Invalid number of arguments"
+                echo $USAGE
+                Cleanup
+                exit 1
+        else
+                # Check if clean operation
+                if [ $2 == $CLEAN_TAG ]; then
+                        # Clean tag added
+                        Verify
+                        Remote_Clean
+                        Cleanup
+                        exit 0
+                fi
         fi
-    fi
 fi
 
 Verify
@@ -124,7 +124,7 @@ echo "Locating files"
 # Find valid files from pattern
 for i in "${FILE_TYPES[@]}"
 do
-    find . -name "*$i" >> $TMP_FILE
+        find . -name "*$i" >> $TMP_FILE
 done
 
 echo "Creating package"
